CREATE TABLE IF NOT EXISTS AdminInformation (
    AdminId INTEGER PRIMARY KEY AUTOINCREMENT,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Address VARCHAR(100) NOT NULL,
    Age TINYINT NOT NULL,
    Email VARCHAR(50) NOT NULL,
    TelephoneNumber VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS AdminLoginInformation (
    AdminId INT NOT NULL,
    AdminUserName VARCHAR(50) NOT NULL,
    AdminPassword VARCHAR(255) NOT NULL,
    Role VARCHAR(50) NOT NULL,
    CONSTRAINT AdmLoginInf_Fk FOREIGN KEY (AdminId) REFERENCES AdminInformation (AdminId) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS AdminLoginLog (
    LogId INTEGER PRIMARY KEY AUTOINCREMENT,
    AdminId INT NOT NULL,
    LoginTimeStamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT AdmLoginLog_Fk FOREIGN KEY (AdminId) REFERENCES AdminInformation (AdminId) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS AdminToken (
    TokenId INTEGER PRIMARY KEY AUTOINCREMENT,
    AdminId INT NOT NULL,
    TokenHash VARCHAR(255) NOT NULL,
    ExpiresAt DATETIME NOT NULL,
    CreateAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    RevokeStatus BOOLEAN DEFAULT 0,
    CONSTRAINT AdmTkn_Fk FOREIGN KEY (AdminId) REFERENCES AdminInformation (AdminId) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Category (
    CategoryId INTEGER PRIMARY KEY AUTOINCREMENT,
    Category VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Color (
    ColorId INTEGER PRIMARY KEY AUTOINCREMENT,
    ColorName VARCHAR(50) NOT NULL,
    HexCode VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS Material (
    MaterialId INTEGER PRIMARY KEY AUTOINCREMENT,
    MaterialName VARCHAR(50) NOT NULL,
    MaterialType VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Member (
    MemberId INTEGER PRIMARY KEY AUTOINCREMENT,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    PhoneNumber VARCHAR(15) NOT NULL,
    MemberEmail VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS MemberLoginInformation (
    MemberId INT NOT NULL PRIMARY KEY,
    MemberPassword VARCHAR(255) NOT NULL,
    CONSTRAINT MemLoginInf_Fk FOREIGN KEY (MemberId) REFERENCES Member (MemberId) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS MemberLoginLog (
    LogId INTEGER PRIMARY KEY AUTOINCREMENT,
    MemberId INT NOT NULL,
    LoginTimeStamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT MemLoginLog_Fk FOREIGN KEY (MemberId) REFERENCES Member (MemberId) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Address (
    AddressId INTEGER PRIMARY KEY AUTOINCREMENT,
    MemberId INT NOT NULL,
    AddressDetail VARCHAR(100) NOT NULL,
    CONSTRAINT Addr_Fk FOREIGN KEY (MemberId) REFERENCES Member (MemberId) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Delivery (
    TrackingId INTEGER PRIMARY KEY AUTOINCREMENT,
    AddressId INT NOT NULL,
    Status VARCHAR(50) NOT NULL,
    CONSTRAINT Del_Fk FOREIGN KEY (AddressId) REFERENCES Address (AddressId)
);

CREATE TABLE IF NOT EXISTS Orders (
    OrderId INTEGER PRIMARY KEY AUTOINCREMENT,
    MemberId INT NOT NULL,
    TrackingId INT NOT NULL,
    ContactEmail VARCHAR(50),
    TotalAmount DECIMAL(10, 2) NOT NULL,
    VatAmount DECIMAL(10, 2) NOT NULL,
    OrderDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT OrdMem_Fk FOREIGN KEY (MemberId) REFERENCES Member (MemberId),
    CONSTRAINT OrdTrk_Fk FOREIGN KEY (TrackingId) REFERENCES Delivery (TrackingId)
);

CREATE TABLE IF NOT EXISTS Product (
    ProductId INTEGER PRIMARY KEY AUTOINCREMENT,
    CategoryId INT NOT NULL,
    ProductName VARCHAR(100) NOT NULL,
    Price DECIMAL(10, 2) NOT NULL,
    QuantityLeft INT DEFAULT 0,
    ProductDescription VARCHAR(255) NOT NULL,
    ProductDetail VARCHAR(255) NOT NULL,
    WidthDimension DECIMAL(7, 2) DEFAULT 0,
    HeightDimension DECIMAL(7, 2) DEFAULT 0,
    LengthDimension DECIMAL(7, 2) DEFAULT 0,
    Weight DECIMAL(7, 2) DEFAULT 0,
    Featured BOOLEAN DEFAULT 0,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    MaterialId INT,
    CONSTRAINT ProdCate_Fk FOREIGN KEY (CategoryId) REFERENCES Category (CategoryId),
    CONSTRAINT ProdMat_Fk FOREIGN KEY (MaterialId) REFERENCES Material (MaterialId)
);

CREATE TABLE IF NOT EXISTS Review (
    ReviewId INTEGER PRIMARY KEY AUTOINCREMENT,
    ProductId INT NOT NULL,
    MemberId INT NOT NULL,
    Rating TINYINT NOT NULL,
    ReviewComment VARCHAR(255),
    CONSTRAINT ReviewProd_Fk FOREIGN KEY (ProductId) REFERENCES Product (ProductId),
    CONSTRAINT ReviewMem_Fk FOREIGN KEY (MemberId) REFERENCES Member (MemberId)
);

CREATE TABLE IF NOT EXISTS Image (
    ImageId INTEGER PRIMARY KEY AUTOINCREMENT,
    ProductId INT NOT NULL,
    ImageUrl VARCHAR(255),
    CONSTRAINT ImgProd_Fk FOREIGN KEY (ProductId) REFERENCES Product (ProductId)
);

CREATE TABLE IF NOT EXISTS OrderItem (
    ProductId INT NOT NULL,
    OrderId INT NOT NULL,
    ItemQuantity INT NOT NULL,
    PRIMARY KEY (ProductId, OrderId)
);

CREATE TABLE IF NOT EXISTS ProductColor (
    ProductId INT NOT NULL,
    ColorId INT NOT NULL,
    PRIMARY KEY (ProductId, ColorId)
);

CREATE TABLE IF NOT EXISTS Contactors (
    ContactorId INTEGER PRIMARY KEY AUTOINCREMENT,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    Email VARCHAR(50),
    Message VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS NewsLetterSubscriber (
    SubscriberId INTEGER PRIMARY KEY AUTOINCREMENT,
    Email VARCHAR(50)
);
